// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMpwSSWZoXe-ZT-0zuS-yDhOj3CY1-aO0',
    appId: '1:576025833218:web:205ffc22ba6d3a7a081c1b',
    messagingSenderId: '576025833218',
    projectId: 'bookings-b3ebd',
    authDomain: 'bookings-b3ebd.firebaseapp.com',
    storageBucket: 'bookings-b3ebd.appspot.com',
    measurementId: 'G-KGVH9HK19Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBYnP1zZRmNxD-4rtaTd9UR6Mt8DwKu7k',
    appId: '1:576025833218:android:1fc73989b4f82dc3081c1b',
    messagingSenderId: '576025833218',
    projectId: 'bookings-b3ebd',
    storageBucket: 'bookings-b3ebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAC4XWew3F1Wj5Fk8ZJ0Tmraol7tL_I0',
    appId: '1:576025833218:ios:4e8147d9b2bbe38d081c1b',
    messagingSenderId: '576025833218',
    projectId: 'bookings-b3ebd',
    storageBucket: 'bookings-b3ebd.appspot.com',
    iosClientId: '576025833218-i6raoe82v641en1iinkldtpiq0734kbr.apps.googleusercontent.com',
    iosBundleId: 'com.gospel-crowd.bookings',
  );
}
